site_name: Veto WebApp Docs
theme:
  name: material
  palette:
      - scheme: slate
        primary: indigo
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      - scheme: default
        primary: indigo
        toggle:
          icon: material/weather-night
          name: Switch to dark mode

nav:
  - Home: index.md
  - Philosophy: philosophy.md
  - API: api.md
  - Architecture: architecture.md