site_name: Veto WebApp Docs
theme:
  name: material
  palette:
      - scheme: slate
        primary: indigo
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
      - scheme: default
        primary: indigo
        toggle:
          icon: material/weather-night
          name: Switch to dark mode

nav:
  - Home: index.md
  - API: api.md
  - Architecture: architecture.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
