# Generated by Django 5.2.5 on 2025-08-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=64)),
                ('team_b', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('modes', models.ManyToManyField(blank=True, related_name='maps', to='veto.gamemode')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('ban', 'Ban'), ('pick', 'Pick')], max_length=8)),
                ('team', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veto.gamemode')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veto.map')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='veto.series')),
            ],
            options={
                'ordering': ['step', 'id'],
                'unique_together': {('series', 'step')},
            },
        ),
    ]
