# Generated by Django 5.2.5 on 2025-08-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='is_objective',
            field=models.BooleanField(default=False),
        ),
    ]
