# Generated by Django 5.2.5 on 2025-08-16 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veto', '0002_gamemode_is_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ban_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='round_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='ruleset',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='series',
            name='series_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='series',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('SERIES_SETUP', 'Series Setup'), ('BAN_PHASE', 'Ban Phase'), ('PICK_WINDOW', 'Pick Window'), ('SERIES_COMPLETE', 'Series Complete'), ('ABORTED', 'Aborted')], default='IDLE', max_length=32),
        ),
        migrations.AddField(
            model_name='series',
            name='turn',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SeriesBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField()),
                ('by_team', models.CharField(max_length=1)),
                ('kind', models.CharField(choices=[('OBJECTIVE_COMBO', 'Objective + Map'), ('SLAYER_MAP', 'Slayer Map')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veto.map')),
                ('objective_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veto.gamemode')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='veto.series')),
            ],
            options={
                'ordering': ['step_index', 'id'],
                'unique_together': {('series', 'step_index')},
            },
        ),
        migrations.CreateModel(
            name='SeriesRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('slot_type', models.CharField(choices=[('OBJECTIVE', 'Objective'), ('SLAYER', 'Slayer')], max_length=16)),
                ('pick_by', models.CharField(blank=True, max_length=1)),
                ('locked', models.BooleanField(default=False)),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veto.gamemode')),
                ('pick_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veto.map')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='veto.series')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('series', 'order')},
            },
        ),
    ]
